name: Cut Tag & Release
permissions:
  contents: write # Required for pushing tags and creating releases

on:
  workflow_dispatch:
    inputs:
      version-level:
        description: "Version bump level"
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
        default: patch

env:
  NODE_VERSION: "22.22.0"
  ARTIFACTORY_HOSTNAME: ${{ vars.ARTIFACTORY_HOSTNAME }}
  ARTIFACTORY_TOKEN: ${{ secrets.ARTIFACTORY_TOKEN }}

run-name: Cut ${{ inputs.version-level }} tag by @${{ github.triggering_actor }}

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.cut-tag.outputs.version }}
      tag: ${{ steps.cut-tag.outputs.tag }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: p6m-actions/js-pnpm-setup@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cut Tag
        id: cut-tag
        uses: p6m-actions/js-pnpm-cut-tag@v1
        with:
          version-level: ${{ github.event.inputs.version-level }}

      - name: Output Version Info
        run: echo "Released version ${{ steps.cut-tag.outputs.version }} with tag ${{ steps.cut-tag.outputs.tag }}" | tee -a $GITHUB_STEP_SUMMARY

      - name: Login to Docker Repository
        uses: p6m-actions/docker-repository-login@v1
        with:
          registry: ${{ vars.ARTIFACTORY_HOSTNAME }}
          username: ${{ secrets.ARTIFACTORY_USERNAME }}
          password: ${{ secrets.ARTIFACTORY_IDENTITY_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: p6m-actions/docker-buildx-setup@v1

      - name: Build and Publish Docker Image
        id: docker-publish
        uses: p6m-actions/docker-buildx-build-publish@v1
        with:
          image-name: one-ashley-host-frontend-server
          image-tag: ${{ steps.cut-tag.outputs.version || format('dev-{0}', github.sha) }}
          registry: ${{ vars.ARTIFACTORY_HOSTNAME }}/${{ vars.ARTIFACTORY_PROJECT }}-docker-local/applications
          platforms: linux/amd64,linux/arm64
          push: ${{ github.ref_name == 'main' }}
          skip-setup: true
          builder-name: ${{ steps.buildx.outputs.name }}
          secrets: |
            ARTIFACTORY_HOSTNAME=${{ vars.ARTIFACTORY_HOSTNAME }}
            ARTIFACTORY_TOKEN=${{ secrets.ARTIFACTORY_TOKEN }}
            artifactory-token=${{ secrets.ARTIFACTORY_TOKEN }}
            artifactory-username=${{ secrets.ARTIFACTORY_USERNAME }}
            artifactory-identity-token=${{ secrets.ARTIFACTORY_IDENTITY_TOKEN }}

      - name: Make Artifacts
        if: github.ref_name == 'main'
        run: |
          echo '${{ steps.docker-publish.outputs.image-digest }}' | tee digest.txt

      - name: Create Github Release
        uses: ncipollo/release-action@v1
        if: github.ref_name == 'main'
        with:
          name: Version ${{ steps.cut-tag.outputs.version }}
          tag: ${{ steps.cut-tag.outputs.tag }}
          makeLatest: true
          artifacts: "digest.txt"
          removeArtifacts: true
          generateReleaseNotes: true
          body: |
            Application version: `${{ steps.cut-tag.outputs.version }}`
            Docker image digest: `${{ steps.docker-publish.outputs.image-digest }}`