name: Cut Tag & Release
permissions:
  contents: write # Required for pushing tags and creating releases
  id-token: write # Required by token-exchange inside python-uv-cut-tag

on:
  workflow_dispatch:
    inputs:
      version-level:
        description: "Version bump level"
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
        default: patch

run-name: Cut ${{'{'}}{inputs.version-level }} tag by @${{'{'}}{github.triggering_actor }}

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      version: ${{'{'}}{steps.cut-tag.outputs.version }}
      tag: ${{'{'}}{steps.cut-tag.outputs.tag }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python and uv
        uses: p6m-actions/python-uv-setup@v1
        with:
          python-version: "3.11"

      - name: Login to Python Repository
        uses: p6m-actions/python-uv-repository-login@v1
        with:
          credentials: |
            artifactory=${{'{'}}{secrets.P6M_ARTIFACTORY_USERNAME }}:${{'{'}}{secrets.P6M_ARTIFACTORY_IDENTITY_TOKEN }}

      - name: Cut Tag
        id: cut-tag
        uses: p6m-actions/python-uv-cut-tag@v1
        with:
          version-level: ${{'{'}}{github.event.inputs.version-level }}

      - name: Output Version Info
        run: echo "Released version ${{'{'}}{steps.cut-tag.outputs.version }} with tag ${{'{'}}{steps.cut-tag.outputs.tag }}" | tee -a $GITHUB_STEP_SUMMARY

      - name: Login to Docker Repository
        uses: p6m-actions/docker-repository-login@v1
        with:
          registry: ${{'{'}}{vars.P6M_ARTIFACTORY_HOSTNAME }}
          username: ${{'{'}}{secrets.P6M_ARTIFACTORY_USERNAME }}
          password: ${{'{'}}{secrets.P6M_ARTIFACTORY_IDENTITY_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Publish Docker Image
        id: docker-publish
        uses: docker/build-push-action@v6
        with:
          tags: ${{'{'}}{vars.P6M_ARTIFACTORY_HOSTNAME }}/${{'{'}}{vars.P6M_ARTIFACTORY_PROJECT }}-docker-local/applications/{{ prefix-name }}-{{ suffix-name }}-server:${{'{'}}{steps.cut-tag.outputs.version }}
          platforms: linux/amd64,linux/arm64
          push: ${{'{'}}{github.ref_name == 'main' }}
          secrets: |
            artifactory-username=${{'{'}}{secrets.P6M_ARTIFACTORY_USERNAME }}
            artifactory-identity-token=${{'{'}}{secrets.P6M_ARTIFACTORY_IDENTITY_TOKEN }}

      - name: Make Artifacts
        if: github.ref_name == 'main'
        run: |
          echo '${{'{'}}{steps.docker-publish.outputs.digest }}' | tee digest.txt

      - name: Create Github Release
        uses: ncipollo/release-action@v1
        if: github.ref_name == 'main'
        with:
          name: Version ${{'{'}}{steps.cut-tag.outputs.version }}
          tag: ${{'{'}}{steps.cut-tag.outputs.tag }}
          makeLatest: true
          artifacts: "digest.txt"
          removeArtifacts: true
          generateReleaseNotes: true
          body: |
            Application version: `${{'{'}}{steps.cut-tag.outputs.version }}`
            Docker image digest: `${{'{'}}{steps.docker-publish.outputs.digest }}`
